apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2019-07-16T12:17:10Z
  generation: 1
  labels:
    run: chsos-server
  name: chsos-server
  namespace: default
  resourceVersion: "69262"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/chaos-server
  uid: a2d024e5-a7c3-11e9-be4e-068f39690a0e
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: chsos-server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: chsos-server
    spec:
      containers:
      - image: royptikal/chaos-server
        imagePullPolicy: Always
        name: chsos-server
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: 2019-07-16T12:17:10Z
    lastUpdateTime: 2019-07-16T12:17:10Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
